language: python

sudo: required
cache: pip
dist: "bionic"

services:
  - mysql

python:
  - '2.7'
  - '3.6'
  - '3.7'
  - 'pypy3.5'

matrix:
  allow_failures:
    - python: 'pypy3.5'

install:
  - pip install -e .

before_script:
  - pip install coverage
  - pip install codecov

before_install:
  - mysql -e 'create database pydal;'

script: export COVERAGE_PROCESS_START=gluon/tests/coverage.ini; ./web2py.py --run_system_tests --with_coverage

after_success:
  - coverage combine;
  - codecov

deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgENdGVzdC5weXBpLm9yZwIkMmRjMTFmYTEtOWU0Ny00OTczLTlmMGYtYTk1YTNmOTg2MTA1AAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiDaEJfqPfnIzpBfWc48o9K6dE5bQpdvADB7LCOGHYfFPg"
  server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
  skip_cleanup: true
  on: # when all conditions in 'on' block are met, it will deploy
    branch: master
    # condition: ... 
    # tags: true -- can tell travis to only deploy to PyPI when a new package is out, i.e one with tags

notifications:
  email: true
